### ISSUE TITLE
Null reference exception with GetComputedStyle when the source is a string

### ISSUE THREAD

**Issue by Tony20221** [AngleSharp/AngleSharp.Css#112]
I have this code which runs fine.          
 
```
    var config = Configuration.Default.WithDefaultLoader().WithCss();
            //var context = BrowsingContext.New(Configuration.Default);
            var context = BrowsingContext.New(config);

//            var document = context.OpenAsync(req => req.Content(html)).Result;
         var document = context.OpenAsync("https://www.google.com").Result;

            var element = document.All.Where(m => m.LocalName == "input" && m.HasAttribute("value") && !string.IsNullOrEmpty(m.GetAttribute("value"))).First();
            var style = document.DefaultView.GetComputedStyle(element);
```

When I switch the code to use the 'html' variable  instead of opening the Google web page, I get a null object reference exception in the line with GetComputedStyle method. document and DefaultView and element are not null.
The variable 'html' is a string which contains the html of the page after it has been rendered.

What am I missing?

This is the stack trace:
"Object reference not set to an instance of an object."
   at AngleSharp.Css.FeatureValidators.WidthFeatureValidator.Validate(IMediaFeature feature, IRenderDevice renderDevice)
   at AngleSharp.Css.Dom.MediaListExtensions.Validate(IMediaFeature feature, IRenderDevice device)
   at AngleSharp.Css.Dom.MediaListExtensions.<>c__DisplayClass5_0.<Validate>b__0(IMediaFeature m)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AngleSharp.Css.Dom.MediaListExtensions.Validate(ICssMedium medium, IRenderDevice device)
   at AngleSharp.Css.Dom.MediaListExtensions.<>c__DisplayClass4_0.<Validate>b__0(ICssMedium m)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AngleSharp.Css.Dom.MediaListExtensions.Validate(IMediaList list, IRenderDevice device)
   at AngleSharp.Dom.StyleSheetExtensions.<GetMatchingStyles>d__1.MoveNext()
   at AngleSharp.Css.Dom.StyleCollection.<GetEnumerator>d__5.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__17.MoveNext()
   at AngleSharp.Css.StyleCollectionExtensions.ComputeCascadedStyle(IEnumerable`1 styleCollection, IElement element, ICssStyleDeclaration parent)
   at AngleSharp.Css.StyleCollectionExtensions.ComputeDeclarations(IEnumerable`1 rules, IElement element, String pseudoSelector)
   at AngleSharp.Dom.WindowExtensions.GetComputedStyle(IWindow window, IElement element, String pseudo)

**Comment by FlorianRappl** [comment]
Hm did you read the docs?

> Furthermore, for some CSSOM features (e.g., media queries) a render device is required.

```cs
var config = Configuration.Default
    .WithCss()
    .WithRenderDevice(new DefaultRenderDevice
    {
        DeviceHeight = 768,
        DeviceWidth = 1024,
    });
```

Hope that helps!

(See https://github.com/AngleSharp/AngleSharp.Css#basic-configuration)

**Comment by FlorianRappl** [comment]
> I am not talking about what kind of css functionality is being used. It's about the need for a rendering device when the input is a straight string but it's not needed when opening a web page

I may be confused here. Just to be straight. The exception is thrown because *you* did actually *demand* from AngleSharp to `GetComputedStyle`. The exception would **not** be thrown if you did not do that. Just parsing the DOM does not involve any style tree computations. Yes, CSS is parsed if its active - but parsing CSS is not the same as actively calculating styles (which would be necessary for the render tree).

> I mean when you request a webpage, you're getting back html from the web server. The fact that there's a clear distinction between how AngleSharp deals with the two cases is not evident in the docs.

This is not what you are doing. You are already way beyond getting back HTML from somewhere. You are already dealing with the resulting DOM, which is (originally) based on this string, but not this string. It's a live model with an API in front - calling things on the API will trigger some functionality and when *you* want to trigger a style calculation the engine needs to have all the information to actually perform the calculation. Simple as that.

The only reason the exception was emitted in one case and not the other is that in one case there have been no CSS nodes that actually required no render device. This is as simple as: If you loop over nothing then nothing happens.
