### ISSUE TITLE
Using a @media rule without explicitly registering an IRenderDevice causes a NullReferenceException

### ISSUE THREAD

**Issue by poizan42** [AngleSharp/AngleSharp.Css#20]
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (if its an issue with the core library, please report to `AngleSharp` directly)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

Attempting to call ComputeCurrentStyle() when any @media rules are defined causes a NullReferenceException to be thrown at:

```
   at AngleSharp.Css.Dom.MediaListExtensions.IsInvalid(ICssMedium medium, IRenderDevice device, String keyword, DeviceCategory category) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\MediaListExtensions.cs:line 60
   at AngleSharp.Css.Dom.MediaListExtensions.IsInvalid(ICssMedium medium, IRenderDevice device) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\MediaListExtensions.cs:line 53
   at AngleSharp.Css.Dom.MediaListExtensions.Validate(ICssMedium medium, IRenderDevice device) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\MediaListExtensions.cs:line 48
   at AngleSharp.Css.Dom.MediaListExtensions.<>c__DisplayClass4_0.<Validate>b__0(ICssMedium m) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\MediaListExtensions.cs:line 38
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AngleSharp.Css.Dom.MediaListExtensions.Validate(IMediaList list, IRenderDevice device) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\MediaListExtensions.cs:line 38
   at AngleSharp.Css.Dom.ValidationExtensions.IsValid(ICssMediaRule rule, IRenderDevice device) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\ValidationExtensions.cs:line 30
   at AngleSharp.Css.Dom.StyleCollection.<GetRules>d__6.MoveNext() in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Dom\Internal\StyleCollection.cs:line 68
   at AngleSharp.Css.Dom.StyleCollection.<GetEnumerator>d__5.MoveNext() in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Dom\Internal\StyleCollection.cs:line 48
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at AngleSharp.Css.Extensions.StyleCollectionExtensions.ComputeCascadedStyle(StyleCollection styleCollection, IElement element) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Dom\StyleCollectionExtensions.cs:line 77
   at AngleSharp.Css.Extensions.StyleCollectionExtensions.ComputeDeclarations(StyleCollection rules, IElement element, String pseudoSelector) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Dom\StyleCollectionExtensions.cs:line 54
   at AngleSharp.Dom.WindowExtensions.GetComputedStyle(IWindow window, IElement element, String pseudo) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\WindowExtensions.cs:line 55
   at AngleSharp.Dom.CssApiExtensions.ComputeCurrentStyle(IElement element) in D:\projects\AngleSharp.Css\src\AngleSharp.Css\Extensions\CssApiExtensions.cs:line 27
   at AngleSharpTest.Program.MediaQueryCss() in D:\projects\Test2\AngleSharpTest\Program.cs:line 109
```

### Steps to Reproduce

Compile and run a program calling MediaRuleCss:

```CSharp
    private static void MediaRuleCss()
    {
      var browsingContext = BrowsingContext.New(Configuration.Default.WithCss());
      var htmlParser = browsingContext.GetService<IHtmlParser>();
      var document = htmlParser.ParseDocument("<html><head><style>@media screen { }</style></head><body></body></html>");
      document.Body.ComputeCurrentStyle();
    }
```

**Expected behavior:**
Not getting a NullReferenceException. By default it should probably be assumed that the device is a screen.

**Actual behavior:**
Got NullReferenceException

**Environment details:**
.NET 4.7.2, Windows 10.0.18334.1]

### Possible Solution

The only implementation of IRenderDevice included in AngleSharp.Css currently is MockRenderDevice which is only used for tests. I think a DefaultRenderDevice should be registered with some sane default values (i.e. there should just be hardcoded defaults independent on where the code is running if the goal isn't to render anything anyways).

**Comment by FlorianRappl** [comment]
This is a good point. Potentially, the same solution as for #21 would work (having an `IRenderDevice` in the config by default), however, I think we can also do something else: If an `IRenderDevice` was found in the config (by default none will be registered / found) then this should be used; otherwise same default value for the requested properties of the render device will be used.

Yes, such a mechanism scatters the default values a bit, however, makes it resilient against *not having any* render device registered (e.g., when somebody forcefully removes it or tries to register all CSS relevant services individually).

Any preference here?

**Comment by poizan42** [comment]
I think that the cleanest solution might be to define a default implementation, because otherwise all consumers have to take care to handle the case when there is no IRenderDevice and supply their own default values. If you forcibly removes the thing providing information about the "device" target then you are kinda asking that things using this does not work as expected. I don't necessarily mean that just throwing a NullReferenceException is the best result, but code using it could just bail out if there is no IRenderDevice, e.g. in this case it would mean that any @media rule would be ignored.

**Comment by FlorianRappl** [comment]
Hm, but that's the thing - define a *default implementation* (which needs to be placed in the configuration and will eventually lead to null ref exceptions if removed / not added) or define *default values*. I actually tend to go for the latter as it makes it very robust.

But maybe the ultimate best solution is to have both - a default / flexible implementation that is added via `WithCss`, but the default values - if really nothing is there. Makes it transparent, flexible, yet robust. Of course, highest implementation effort.

**Comment by FlorianRappl** [comment]
Landed in `devel`.

Note: Fixed the bug with a simple check - a default implementation of `IRenderDevice` should still be supplied, but would be done in a different story (GH issue ref).
