### ISSUE TITLE
CSS rule with only `grid-template-areas` throws exception when requesting `CssText`

### ISSUE THREAD

**Issue by singingknight** [AngleSharp/AngleSharp.Css#27]
### Description

CSS rule with only `grid-template-areas` throws exception when requesting `CssText`

### Steps to Reproduce
```cs
[Test]
public void CssRuleWithOnlyGridTemplateAreasLegal()
{
	var snippet = @"div#A { grid-template-areas: ""a b b"" ""a c d"" }";
	var rule = ParseRule(snippet);
	var text  = rule.CssText;
	Assert.AreEqual(snippet, text);
}
```

**Expected behavior:**
Test should pass

**Actual behavior:**
Crash with exception:
```
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at AngleSharp.Css.Values.GridTemplate.get_CssText() in c:\work\AngleSharp.Css\src\AngleSharp.Css\Values\GridTemplate.cs:line 67
   at AngleSharp.Css.Dom.CssProperty.get_Value() in c:\work\AngleSharp.Css\src\AngleSharp.Css\Dom\Internal\CssProperty.cs:line 49
   at AngleSharp.Css.Dom.CssProperty.ToCss(TextWriter writer, IStyleFormatter formatter) in c:\work\AngleSharp.Css\src\AngleSharp.Css\Dom\Internal\CssProperty.cs:line 124
   at AngleSharp.Css.CssStyleFormatter.AngleSharp.IStyleFormatter.BlockDeclarations(IEnumerable`1 declarations)
   at AngleSharp.Css.Dom.CssStyleDeclaration.ToCssBlock(IStyleFormatter formatter) in c:\work\AngleSharp.Css\src\AngleSharp.Css\Dom\Internal\CssStyleDeclaration.cs:line 192
   at AngleSharp.Css.Dom.CssStyleRule.ToCss(TextWriter writer, IStyleFormatter formatter) in c:\work\AngleSharp.Css\src\AngleSharp.Css\Dom\Internal\Rules\CssStyleRule.cs:line 64
   at AngleSharp.FormatExtensions.ToCss(IStyleFormattable style, IStyleFormatter formatter)
   at AngleSharp.Css.Dom.CssRule.get_CssText() in c:\work\AngleSharp.Css\src\AngleSharp.Css\Dom\Internal\CssRule.cs:line 36
```

**Comment by FlorianRappl** [comment]
Works already in `devel`. Added the test to protect against regression.
