### ISSUE TITLE
FormatException in ColorParse

### ISSUE THREAD

**Issue by ahazelwood** [AngleSharp/AngleSharp.Css#33]
# Issue Templates

Please use one of the following templates to create your issue:

- [BUG REPORT](https://github.com/AngleSharp/AngleSharp.Css/issues/new?template=bugs.md)
- [FEATURE PROPOSAL](https://github.com/AngleSharp/AngleSharp.Css/issues/new?template=features.md)

Getting the following exception information on parsing some html.  No chance to recover exists because exception breaks parsing.  Stack trace is:

```
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at AngleSharp.Css.Parser.ColorParser.ParseRgbComponent(StringSource source)
   at AngleSharp.Css.Parser.ColorParser.ParseRgba(StringSource source)
   at AngleSharp.Css.Parser.ColorParser.Start(StringSource source)
   at AngleSharp.Css.Parser.ColorParser.ParseColor(StringSource source)
   at AngleSharp.Css.Converters.StructValueConverter`1.Convert(StringSource source)
   at AngleSharp.Css.Converters.OrValueConverter.Convert(StringSource source)
   at AngleSharp.Css.Converters.ValueConverterExtensions.Convert(IValueConverter converter, String value)
   at AngleSharp.Css.Dom.CssProperty.set_Value(String value)
   at AngleSharp.Css.Dom.CssStyleDeclaration.SetProperty(String propertyName, String propertyValue, String priority)
   at AngleSharp.Css.Parser.CssBuilder.CreateDeclarationWith(ICssProperties properties, CssToken& token)
   at AngleSharp.Css.Parser.CssBuilder.FillDeclarations(CssStyleDeclaration style, CssToken token)
   at AngleSharp.Css.Parser.CssParser.Parse[T](String source, Func`3 create)
   at AngleSharp.Css.Dom.CssStyleDeclaration.Update(String value)
   at AngleSharp.Css.Dom.ElementCssInlineStyleExtensions.CreateStyle(IElement element, String source)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at AngleSharp.Css.StyleAttributeObserver.AngleSharp.Dom.IAttributeObserver.NotifyChange(IElement host, String name, String value)
   at AngleSharp.Dom.Element.SetupElement()
   at AngleSharp.Html.Parser.HtmlDomBuilder.CloseCurrentNode()
   at AngleSharp.Html.Parser.HtmlDomBuilder.InBodyEndTagAnythingElse(HtmlTagToken tag)
   at AngleSharp.Html.Parser.HtmlDomBuilder.InBodyEndTag(HtmlTagToken tag)
   at AngleSharp.Html.Parser.HtmlDomBuilder.Parse(HtmlParserOptions options)
   at AngleSharp.Html.Parser.HtmlParser.Parse(HtmlDocument document)
   at CI. <snipped>
```

Appears to be because of the numeric.Parse functions.  At the very least the exceptions should be caught and null returned.

Thanks.

**Comment by FlorianRappl** [comment]
What is the input?

Please provide an [MWE](https://en.wikipedia.org/wiki/Minimal_working_example). Thanks!

**Comment by ahazelwood** [comment]
It was some random web page (not sure which one) that I came across.  In tracking it down, I did notice that no exceptions were being caught around the number parsing, so probably a good fix to implement.  I’ll let you know if I come across it again.

**Comment by FlorianRappl** [comment]
Solved in `devel`.
